server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/charvaq
    username: postgres
    password: 123

    main:
      allow-bean-definition-overriding: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
#spring.main.lazy-initialization=true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

